#!/bin/sh
#
# An example hook script to check the commit log message.
# Called by "git commit" with one argument, the name of the file
# that has the commit message.  The hook should exit with non-zero
# status after issuing an appropriate message if it wants to stop the
# commit.  The hook is allowed to edit the commit message file.
#
# To enable this hook, rename this file to "commit-msg".

# Uncomment the below to add a Signed-off-by line to the message.
# Doing this in a hook is a bad idea in general, but the prepare-commit-msg
# hook is more suited to it.
#
# SOB=$(git var GIT_AUTHOR_IDENT | sed -n 's/^\(.*>\).*$/Signed-off-by: \1/p')
# grep -qs "^$SOB" "$1" || echo "$SOB" >> "$1"

# This example catches duplicate Signed-off-by lines.

allowed_types='feat|docs|util|build|chore|style|refactor|test|perf|fix'

if ! awk '
    !/^('$allowed_types')(\([a-z]+\))?: [a-z]/ {exit 1}
    {exit 0}
' "$1"
then
    echo "\nError: commit message doesn't follow conventional commit standard:"
    echo ""
    echo "<type>: <description>"
    echo "<type>(<scope>): <description>"
    echo ""
    echo "<type> must match:" $allowed_types
    echo "<description> and <scope> must be lower-case"
    echo ""
    exit 1
fi
